apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app-of-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guestbook-app-of-app
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: appcode/app1
    repoURL: https://github.com/LTFC-TST/app-of-apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
