apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-app-2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-app-2
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-app-2
        tst: v1
    spec:
      containers:
      - image: omniregistry/front-end:d7125a757a203f7646e4c211744a362280a183d5
        name: guestbook-ui-app-2
        ports:
        - containerPort: 80
