apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-app-2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-app-2
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-app-2
        tst: v1
    spec:
      containers:
      - image: omniregistry/front-end:8eeedac3120bc8d37a71c129e5ee0f478c38e3aa
        name: guestbook-ui-app-2
        ports:
        - containerPort: 80
